sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

#sylius_history_plugin_admin:
#    resource: "@SyliusPriceHistoryPlugin/config/admin_routing.yaml"
#    prefix: '/%sylius_admin.path_name%'
